[package]
name = "zed_dockerfile"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/dockerfile.rs"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
zed_extension_api = "0.7.0"
